### ISSUE TITLE
Demo app not working using node version 8.12.0

### ISSUE THREAD

**Issue by jfvaleroso** [flatlogic/sing-app#9]
D:\DESIGN\sing-app>gulp serve
module.js:550
    throw err;
    ^

Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\DESIGN\sing-app\gulpfile.js:5:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by keksonov** [comment]
Hi, you just have to install gulp-sass `npm install gulp-sass`
